-- The application role is distinct from the migration owner and never has BYPASSRLS.
CREATE FUNCTION prevent_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Business history is append-only'; END; $$;
ALTER TABLE "StoreProduct" ADD CONSTRAINT "StoreProduct_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "StoreProduct" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoreProduct" FORCE ROW LEVEL SECURITY;
CREATE POLICY "StoreProduct_scope" ON "StoreProduct" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "InventoryLot" ADD CONSTRAINT "InventoryLot_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "InventoryLot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryLot" FORCE ROW LEVEL SECURITY;
CREATE POLICY "InventoryLot_scope" ON "InventoryLot" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "StockMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockMovement" FORCE ROW LEVEL SECURITY;
CREATE POLICY "StockMovement_scope" ON "StockMovement" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "Sale" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Sale" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Sale_scope" ON "Sale" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "SaleRevision" ADD CONSTRAINT "SaleRevision_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "SaleRevision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SaleRevision" FORCE ROW LEVEL SECURITY;
CREATE POLICY "SaleRevision_scope" ON "SaleRevision" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "PointsAccount" ADD CONSTRAINT "PointsAccount_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "PointsAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PointsAccount" FORCE ROW LEVEL SECURITY;
CREATE POLICY "PointsAccount_scope" ON "PointsAccount" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "PointsEntry" ADD CONSTRAINT "PointsEntry_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "PointsEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PointsEntry" FORCE ROW LEVEL SECURITY;
CREATE POLICY "PointsEntry_scope" ON "PointsEntry" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "Reward" ADD CONSTRAINT "Reward_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "Reward" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reward" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Reward_scope" ON "Reward" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "RewardClaim" ADD CONSTRAINT "RewardClaim_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "RewardClaim" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RewardClaim" FORCE ROW LEVEL SECURITY;
CREATE POLICY "RewardClaim_scope" ON "RewardClaim" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "ReplenishmentOrder" ADD CONSTRAINT "ReplenishmentOrder_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "ReplenishmentOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReplenishmentOrder" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ReplenishmentOrder_scope" ON "ReplenishmentOrder" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "Delivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Delivery" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Delivery_scope" ON "Delivery" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "DeliveryReceipt" ADD CONSTRAINT "DeliveryReceipt_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "DeliveryReceipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeliveryReceipt" FORCE ROW LEVEL SECURITY;
CREATE POLICY "DeliveryReceipt_scope" ON "DeliveryReceipt" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "Alert" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Alert" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Alert_scope" ON "Alert" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "ProcessedOperation" ADD CONSTRAINT "ProcessedOperation_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "ProcessedOperation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProcessedOperation" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ProcessedOperation_scope" ON "ProcessedOperation" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "StoreCursor" ADD CONSTRAINT "StoreCursor_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "StoreCursor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoreCursor" FORCE ROW LEVEL SECURITY;
CREATE POLICY "StoreCursor_scope" ON "StoreCursor" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "Change" ADD CONSTRAINT "Change_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "Change" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Change" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Change_scope" ON "Change" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_store_fk" FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "Announcement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Announcement" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Announcement_scope" ON "Announcement" USING ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true)) WITH CHECK ("organizationId"::text=current_setting('app.organization_id',true) AND "storeId"::text=current_setting('app.store_id',true));
CREATE TRIGGER "StockMovement_immutable" BEFORE UPDATE OR DELETE ON "StockMovement" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
CREATE TRIGGER "SaleRevision_immutable" BEFORE UPDATE OR DELETE ON "SaleRevision" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
CREATE TRIGGER "PointsEntry_immutable" BEFORE UPDATE OR DELETE ON "PointsEntry" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
CREATE TRIGGER "DeliveryReceipt_immutable" BEFORE UPDATE OR DELETE ON "DeliveryReceipt" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
CREATE TRIGGER "AuditEntry_immutable" BEFORE UPDATE OR DELETE ON "AuditEntry" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
CREATE TRIGGER "ProcessedOperation_immutable" BEFORE UPDATE OR DELETE ON "ProcessedOperation" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
CREATE TRIGGER "Change_immutable" BEFORE UPDATE OR DELETE ON "Change" FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation();
ALTER TABLE "Store" ADD CONSTRAINT "Store_organizationId_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"(id);
ALTER TABLE "OrganizationMembership" ADD CONSTRAINT "OrganizationMembership_organizationId_fk" FOREIGN KEY ("organizationId") REFERENCES "Organization"(id);
ALTER TABLE "OrganizationMembership" ADD CONSTRAINT "OrganizationMembership_userId_fk" FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fk" FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fk" FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "StoreProduct" ADD CONSTRAINT "StoreProduct_productId_fk" FOREIGN KEY ("productId") REFERENCES "Product"(id);
ALTER TABLE "InventoryLot" ADD CONSTRAINT "InventoryLot_productId_fk" FOREIGN KEY ("productId") REFERENCES "Product"(id);
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_sellerId_fk" FOREIGN KEY ("sellerId") REFERENCES "User"(id);
ALTER TABLE "PointsEntry" ADD CONSTRAINT "PointsEntry_userId_fk" FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "PointsAccount" ADD CONSTRAINT "PointsAccount_userId_fk" FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "RewardClaim" ADD CONSTRAINT "RewardClaim_userId_fk" FOREIGN KEY ("userId") REFERENCES "User"(id);
ALTER TABLE "Reward" ADD CONSTRAINT "Reward_productId_fk" FOREIGN KEY ("productId") REFERENCES "Product"(id);
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_actorId_fk" FOREIGN KEY ("actorId") REFERENCES "User"(id);
ALTER TABLE "SaleRevision" ADD CONSTRAINT "SaleRevision_editorId_fk" FOREIGN KEY ("editorId") REFERENCES "User"(id);
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_lotId_scope_fk" FOREIGN KEY ("storeId","lotId") REFERENCES "InventoryLot"("storeId",id);
ALTER TABLE "SaleRevision" ADD CONSTRAINT "SaleRevision_saleId_scope_fk" FOREIGN KEY ("storeId","saleId") REFERENCES "Sale"("storeId",id);
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_orderId_scope_fk" FOREIGN KEY ("storeId","orderId") REFERENCES "ReplenishmentOrder"("storeId",id);
ALTER TABLE "DeliveryReceipt" ADD CONSTRAINT "DeliveryReceipt_deliveryId_scope_fk" FOREIGN KEY ("storeId","deliveryId") REFERENCES "Delivery"("storeId",id);
ALTER TABLE "RewardClaim" ADD CONSTRAINT "RewardClaim_rewardId_scope_fk" FOREIGN KEY ("storeId","rewardId") REFERENCES "Reward"("storeId",id);
ALTER TABLE "Membership" ADD CONSTRAINT membership_scope FOREIGN KEY ("organizationId","storeId") REFERENCES "Store"("organizationId",id);
ALTER TABLE "StoreProduct" ADD CHECK ("priceMillimes">=0 AND threshold>=0 AND "pointsPerUnit">=0);
ALTER TABLE "InventoryLot" ADD CHECK (damaged>=0 AND length(batch)>0);
ALTER TABLE "PointsAccount" ADD CHECK (reserved>=0);
ALTER TABLE "Reward" ADD CHECK (cost>0 AND quantity>0);
ALTER TABLE "RewardClaim" ADD CHECK (status IN ('requested','fulfilled','rejected','cancelled') AND cost>0);
CREATE INDEX points_month ON "PointsEntry" ("storeId",kind,"createdAt");
