# Official Cloudflare API ranges, retrieved 2026-09-22. Scoped to the BioBalance HTTPS vhost.
RemoteIPHeader CF-Connecting-IP
RemoteIPTrustedProxy 173.245.48.0/20
RemoteIPTrustedProxy 103.21.244.0/22
RemoteIPTrustedProxy 103.22.200.0/22
RemoteIPTrustedProxy 103.31.4.0/22
RemoteIPTrustedProxy 141.101.64.0/18
RemoteIPTrustedProxy 108.162.192.0/18
RemoteIPTrustedProxy 190.93.240.0/20
RemoteIPTrustedProxy 188.114.96.0/20
RemoteIPTrustedProxy 197.234.240.0/22
RemoteIPTrustedProxy 198.41.128.0/17
RemoteIPTrustedProxy 162.158.0.0/15
RemoteIPTrustedProxy 104.16.0.0/13
RemoteIPTrustedProxy 104.24.0.0/14
RemoteIPTrustedProxy 172.64.0.0/13
RemoteIPTrustedProxy 131.0.72.0/22
RemoteIPTrustedProxy 2400:cb00::/32
RemoteIPTrustedProxy 2606:4700::/32
RemoteIPTrustedProxy 2803:f800::/32
RemoteIPTrustedProxy 2405:b500::/32
RemoteIPTrustedProxy 2405:8100::/32
RemoteIPTrustedProxy 2a06:98c0::/29
RemoteIPTrustedProxy 2c0f:f248::/32
<Location />
    <RequireAny>
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '173.245.48.0/20'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '103.21.244.0/22'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '103.22.200.0/22'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '103.31.4.0/22'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '141.101.64.0/18'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '108.162.192.0/18'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '190.93.240.0/20'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '188.114.96.0/20'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '197.234.240.0/22'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '198.41.128.0/17'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '162.158.0.0/15'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '104.16.0.0/13'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '104.24.0.0/14'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '172.64.0.0/13'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '131.0.72.0/22'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2400:cb00::/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2606:4700::/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2803:f800::/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2405:b500::/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2405:8100::/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2a06:98c0::/29'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '2c0f:f248::/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '127.0.0.1/32'"
        Require expr "%{CONN_REMOTE_ADDR} -ipmatch '::1/128'"
    </RequireAny>
</Location>
