import { assertTestDatabases } from "./test-database.cjs";
import {beforeAll,afterAll,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {PrismaClient} from '@prisma/client';
import {PrismaPg} from '@prisma/adapter-pg';
import {Database} from '../src/shared/infrastructure/database';
import {WorkspaceService} from '../src/modules/tenancy/workspace.service';
import {NotificationsService} from '../src/modules/notifications/notifications.service';
import {PushDeliveryService} from '../src/modules/notifications/infrastructure/push-delivery';
import {JobRunner,scheduleInventoryChecks} from '../src/shared/jobs/job-runner';
import {PrismaUnitOfWork} from '../src/modules/operations/infrastructure/prisma-ledger';
process.env.DATABASE_URL=process.env.TEST_APP_DATABASE_URL??'postgresql://biobalance_app:local-app-only@localhost:54329/biobalance_test';
if(!new URL(process.env.DATABASE_URL).pathname.endsWith('_test'))throw new Error('TEST_DATABASE_REQUIRED');
assertTestDatabases(process.env.DATABASE_URL, process.env.TEST_OWNER_DATABASE_URL ??
  'postgresql://biobalance:local-development-only@localhost:54329/biobalance_test');
const db=new Database(), owner=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.TEST_OWNER_DATABASE_URL??'postgresql://biobalance:local-development-only@localhost:54329/biobalance_test'})});
const org=randomUUID(),store=randomUUID(),product=randomUUID();
const actor=(name:string,admin=false)=>({id:randomUUID(),name,email:`${randomUUID()}@example.test`,platformAdmin:admin});
const manager=actor('Manager'),seller=actor('Seller'),admin=actor('Admin',true);
const service=new NotificationsService(db,new WorkspaceService(db));
const uow=new PrismaUnitOfWork(db);
async function session(userId:string,expired=false){return owner.session.create({data:{userId,tokenHash:randomUUID(),expiresAt:new Date(Date.now()+(expired?-1000:3600000))}});}
beforeAll(async()=>{
  for(const a of [manager,seller,admin])await owner.user.create({data:{...a,passwordHash:'fixture-not-a-login'}});
  await owner.organization.create({data:{id:org,name:'Notifications test'}});
  await owner.store.create({data:{id:store,organizationId:org,name:'Test',address:'Test',city:'Tunis'}});
  for(const a of [manager,seller])await owner.membership.create({data:{organizationId:org,storeId:store,userId:a.id,permissions:a.id===manager.id?['manage','sell','receive']:['sell']}});
  await owner.product.create({data:{id:product,reference:randomUUID(),name:'Expiry test'}});
  await owner.inventoryLot.create({data:{organizationId:org,storeId:store,productId:product,batch:'Expired',expiry:new Date('2020-01-01'),sellable:2}});
});
afterAll(async()=>{await db.$disconnect();await owner.$disconnect();});
it('operational audience, current manager rights, deliberate staff announcements and read authorization',async()=>{
  await uow.run(manager,org,store,ledger=>ledger.notify('notification-test-'+store,'Stock','Private operational text'));
  expect((await service.list(seller)).length).toBe(0);
  expect((await service.list(manager)).length).toBe(1);
  const notice=(await service.list(manager))[0]!;
  const ss=await session(manager.id);const device=await service.device({...manager,sessionId:ss.id},randomUUID(),'android');
  const sends:string[][]=[];
  const push=new PushDeliveryService(db,{async send(tokens){sends.push(tokens);return tokens.map(()=>({success:true}));}});
  await owner.membership.update({where:{storeId_userId:{storeId:store,userId:manager.id}},data:{permissions:['sell']}});
  await push.deliver(notice.id);expect(sends).toHaveLength(0);expect(await service.list(manager)).toHaveLength(0);
  await expect(service.get(manager,notice.id)).rejects.toMatchObject({code:'NOT_FOUND'});
  await owner.membership.update({where:{storeId_userId:{storeId:store,userId:manager.id}},data:{permissions:['manage','sell']}});
  await push.deliver(notice.id);await push.deliver(notice.id);expect(sends).toEqual([[device.token]]);
  await service.announce(manager,org,store,'Formation','Message volontaire','salespeople',randomUUID());
  const announcement=(await service.list(seller))[0]!;expect(announcement.kind).toBe('announcement');
  await expect(service.get(manager,announcement.id)).rejects.toMatchObject({code:'NOT_FOUND'});
  await owner.membership.update({where:{storeId_userId:{storeId:store,userId:seller.id}},data:{active:false}});
  expect(await service.list(seller)).toHaveLength(0);await expect(service.read(seller,announcement.id)).rejects.toMatchObject({code:'NOT_FOUND'});
  await owner.membership.update({where:{storeId_userId:{storeId:store,userId:seller.id}},data:{active:true}});
});
it('push retries only failed sessions, removes invalid tokens and ignores expired/disabled/revoked access',async()=>{
  const n=await owner.notification.create({data:{userId:seller.id,storeId:store,organizationId:org,eventKey:randomUUID(),kind:'announcement',audience:'all',title:'Private',body:'Private'}});
  const live=await session(seller.id),expired=await session(seller.id,true);
  const tokens=['ok','retry','invalid','expired'].map(x=>x+randomUUID());
  for(let i=0;i<tokens.length;i++)await owner.deviceToken.create({data:{userId:seller.id,sessionId:i===3?expired.id:live.id,token:tokens[i]!,platform:'android'}});
  const delivered:string[]=[];let failing=true;
  const push=new PushDeliveryService(db,{async send(batch,data){expect(data).not.toHaveProperty('body');delivered.push(...batch);return batch.map(t=>t===tokens[2]?{success:false,errorCode:'messaging/registration-token-not-registered'}:t===tokens[1]&&failing?{success:false,errorCode:'unavailable'}:{success:true});}});
  await expect(push.deliver(n.id)).rejects.toThrow('PUSH_DELIVERY_FAILED');
  failing=false;await push.deliver(n.id);
  expect(delivered.filter(t=>t===tokens[0])).toHaveLength(1);expect(delivered.filter(t=>t===tokens[1])).toHaveLength(2);expect(delivered).not.toContain(tokens[3]);
  expect(await owner.deviceToken.findUnique({where:{token:tokens[2]}})).toBeNull();
  const late=await owner.notification.create({data:{...n,id:randomUUID(),eventKey:randomUUID()}});
  await owner.session.update({where:{id:live.id},data:{revokedAt:new Date()}});
  const count=delivered.length;await push.deliver(late.id);expect(delivered).toHaveLength(count);
  await owner.user.update({where:{id:seller.id},data:{disabled:true}});await push.deliver(late.id);expect(delivered).toHaveLength(count);
  await owner.user.update({where:{id:seller.id},data:{disabled:false}});
});
it('device registration checks live session and late old-account registration cannot reclaim or remove a token',async()=>{
  const old=await session(manager.id);await owner.session.update({where:{id:old.id},data:{createdAt:new Date('2020-01-01')}});
  const current=await session(seller.id);const token=randomUUID();
  await service.device({...seller,sessionId:current.id},token,'android');
  await expect(service.device({...manager,sessionId:old.id},token,'android')).rejects.toMatchObject({code:'DEVICE_SESSION_OUTDATED'});
  expect((await owner.deviceToken.findUniqueOrThrow({where:{token}})).userId).toBe(seller.id);
  await service.removeDevice({...manager,sessionId:old.id},token);expect(await owner.deviceToken.findUnique({where:{token}})).not.toBeNull();
  await owner.session.update({where:{id:current.id},data:{revokedAt:new Date()}});
  await expect(service.device({...seller,sessionId:current.id},randomUUID(),'android')).rejects.toMatchObject({code:'SESSION_EXPIRED'});
});
it('exclusive claims, lease recovery, stale completion rejection, retry ceiling and redacted diagnostics',async()=>{
  const kind='test-'+randomUUID();let runs=0;
  await owner.job.createMany({data:Array.from({length:4},()=>({kind,key:randomUUID(),payload:{}}))});
  const runner=new JobRunner(db,[kind],async()=>{runs++;});
  await Promise.all(Array.from({length:4},()=>runner.tick()));expect(runs).toBe(4);expect(await runner.tick()).toBe(false);
  const created=await owner.job.create({data:{kind,key:randomUUID(),payload:{}}});
  const old=(await runner.claim())!;expect(old.id).toBe(created.id);
  await owner.job.update({where:{id:old.id},data:{lockedAt:new Date('2020-01-01')}});
  const recovered=(await runner.claim())!;expect(recovered.leaseToken).not.toBe(old.leaseToken);
  expect(await runner.complete(old)).toBe(false);await runner.fail(old,new Error('stale'));
  expect((await owner.job.findUniqueOrThrow({where:{id:old.id}})).status).toBe('running');
  await runner.fail(recovered,new Error('smtp secret@example.test private-token'));
  const retry=await owner.job.findUniqueOrThrow({where:{id:old.id}});expect(retry.status).toBe('pending');expect(retry.lastError).toBe('JOB_EXECUTION_FAILED');expect(retry.availableAt.getTime()).toBeGreaterThan(Date.now());
  await owner.job.update({where:{id:old.id},data:{attempts:7,availableAt:new Date(0)}});
  const last=(await runner.claim())!;await runner.fail(last,new Error('PUSH_DELIVERY_FAILED'));
  expect((await owner.job.findUniqueOrThrow({where:{id:old.id}})).status).toBe('failed');
  expect(await runner.tick()).toBe(false);
  const unrelated=await owner.job.create({data:{kind:'unrelated-'+kind,key:randomUUID(),payload:{}}});expect(await runner.tick()).toBe(false);
  expect((await owner.job.findUniqueOrThrow({where:{id:unrelated.id}})).attempts).toBe(0);
});
it('scheduled checks reuse hourly identities and inventory alerts/audits are idempotent',async()=>{
  const now=new Date('2098-01-01T10:00:00Z');await scheduleInventoryChecks(db,now);await scheduleInventoryChecks(db,now);
  const jobs=await owner.job.findMany({where:{key:`inventory:${store}:2098-01-01T10`}});expect(jobs).toHaveLength(1);
  const id=jobs[0]!.id;
  await uow.run(admin,org,store,ledger=>ledger.checkInventory(id));await uow.run(admin,org,store,ledger=>ledger.checkInventory(id));
  expect(await owner.auditEntry.count({where:{storeId:store,operationId:id}})).toBe(1);
  const count=await owner.notification.count({where:{storeId:store,kind:'operational'}});
  await uow.run(admin,org,store,ledger=>ledger.checkInventory(randomUUID()));
  expect(await owner.notification.count({where:{storeId:store,kind:'operational'}})).toBe(count);
  expect(await owner.alert.count({where:{storeId:store,kind:'expired',active:true}})).toBe(1);
});
